'use server';
/**
 * @fileOverview A Genkit flow that generates clarifying questions or prompts based on user inventory entries.
 *
 * - generateReflectivePrompts - A function that handles the generation of reflective prompts.
 * - GenerateReflectivePromptsInput - The input type for the generateReflectivePrompts function.
 * - GenerateReflectivePromptsOutput - The return type for the generateReflectivePrompts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateReflectivePromptsInputSchema = z.object({
  entryCategory: z
    .enum(['resentments', 'fears', 'harms'])
    .describe('The category of the inventory entry (e.g., "resentments", "fears", "harms").'),
  entryText: z.string().describe('The user-provided text entry from the inventory table.'),
});
export type GenerateReflectivePromptsInput = z.infer<
  typeof GenerateReflectivePromptsInputSchema
>;

const GenerateReflectivePromptsOutputSchema = z.object({
  clarifyingPrompts: z
    .string()
    .describe('A bulleted list of clarifying questions or prompts generated by the AI.'),
});
export type GenerateReflectivePromptsOutput = z.infer<
  typeof GenerateReflectivePromptsOutputSchema
>;

export async function generateReflectivePrompts(
  input: GenerateReflectivePromptsInput
): Promise<GenerateReflectivePromptsOutput> {
  return generateReflectivePromptsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'reflectivePromptsPrompt',
  input: {schema: GenerateReflectivePromptsInputSchema},
  output: {schema: GenerateReflectivePromptsOutputSchema},
  system: `You are a helpful assistant specialized in guiding individuals through a moral inventory process, as described in 12-step programs. Your goal is to generate insightful and reflective questions or prompts based on the user's inventory entry. These questions should help the user to:
1.  Gain deeper insights into their feelings, motivations, and the situation.
2.  Identify their personal responsibility or 'my part' in the situation.
3.  Formulate potential corrective actions or 'turnarounds'.

Focus on encouraging self-reflection and ownership, without judgment. Do not offer solutions, only questions.`,
  prompt: `The user has provided an entry from their '{{entryCategory}}' inventory.
Entry: {{{entryText}}}

Based on this, generate at least 3-5 clarifying questions or prompts. Format them as a bulleted list.`,
});

const generateReflectivePromptsFlow = ai.defineFlow(
  {
    name: 'generateReflectivePromptsFlow',
    inputSchema: GenerateReflectivePromptsInputSchema,
    outputSchema: GenerateReflectivePromptsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
